In [7]:
import instant_ngp
import torch
from importlib import reload

reload(instant_ngp)
x = torch.tensor([1,1,1]).unsqueeze(0)
encoder = instant_ngp.MultiResHashEncoding()
encoder.forward(x)


tensor([[189008, 189008, 189008, 189008, 189008, 189008, 189008, 189008]])
tensor([[521198, 521198, 521198, 521198, 521198, 521198, 521198, 521198]])
tensor([[393686, 393686, 393686, 393686, 393686, 393686, 393686, 393686]])
tensor([[239954, 239954, 239954, 239954, 239954, 239954, 239954, 239954]])
tensor([[411106, 411106, 411106, 411106, 411106, 411106, 411106, 411106]])
tensor([[350608, 350608, 350608, 350608, 350608, 350608, 350608, 350608]])
tensor([[408139, 408139, 408139, 408139, 408139, 408139, 408139, 408139]])
tensor([[123485, 123485, 123485, 123485, 123485, 123485, 123485, 123485]])
tensor([[16676, 16676, 16676, 16676, 16676, 16676, 16676, 16676]])
tensor([[349566, 349566, 349566, 349566, 349566, 349566, 349566, 349566]])
tensor([[268654, 268654, 268654, 268654, 268654, 268654, 268654, 268654]])
tensor([[17237, 17237, 17237, 17237, 17237, 17237, 17237, 17237]])
tensor([[104488, 104488, 104488, 104488, 104488, 104488, 104488, 104488]])
tensor([[208624, 208624, 208624, 208624, 

tensor([[-0.0653,  0.5048, -0.7698, -1.1677,  0.7079,  1.5006, -0.0993, -0.9361,
          0.0071,  1.7009, -0.8266, -0.2731, -0.7069, -1.6500, -1.2617, -0.7527,
         -1.5056, -0.2576, -0.3853, -0.2190,  1.1078,  1.0666, -1.3665,  0.6354,
         -0.6560, -0.4034, -0.0714, -0.6445, -0.6915,  0.7179, -0.8579,  0.3140]],
       grad_fn=<CatBackward0>)