In [1]:
import torch
import numpy as np
import slam
import nerf
import matplotlib.pyplot as plt
from importlib import reload
from torch.utils.data import DataLoader
import pandas as pd
torch.set_printoptions(linewidth=1000)

xFormers not available
xFormers not available


In [2]:
model, matching = slam.get_models()

Loaded SuperPoint model
Loaded SuperGlue model ("indoor" weights)


In [3]:
reload(slam)
data = slam.training_preprocessor(
    image_prefix="indoor2", 
    model=model,
    matching=matching,
    force_reload=False)

In [4]:
data.shape

torch.Size([1341620, 9])

In [5]:
2**14

16384

In [6]:
518 * 518 / (2**14)

16.377197265625

In [7]:
data_loader = DataLoader(data, batch_size=2**14, shuffle=True)

In [8]:
nerf_model = nerf.NeRFModel()

In [9]:
# nerf.train(model=nerf_model, data_loader=data_loader)


# Epoch 1/25: 100%|██████████| 82/82 [16:58<00:00, 12.42s/batch, loss=0.0685]
# Epoch 1/25, Average Loss: 0.0685222507340879
# Epoch 2/25: 100%|██████████| 82/82 [18:17<00:00, 13.39s/batch, loss=0.0594]
# Epoch 2/25, Average Loss: 0.05939628292874592
# Epoch 3/25: 100%|██████████| 82/82 [12:19<00:00,  9.01s/batch, loss=0.047] 
# Epoch 3/25, Average Loss: 0.04696446302823904
# Epoch 4/25: 100%|██████████| 82/82 [12:26<00:00,  9.11s/batch, loss=0.0356]
# Epoch 4/25, Average Loss: 0.035643301563473735
# Epoch 5/25: 100%|██████████| 82/82 [12:21<00:00,  9.04s/batch, loss=0.0298]
# Epoch 5/25, Average Loss: 0.02981070892476454
# Epoch 6/25: 100%|██████████| 82/82 [12:26<00:00,  9.11s/batch, loss=0.0272]
# Epoch 6/25, Average Loss: 0.027162288497315674
# Epoch 7/25: 100%|██████████| 82/82 [12:14<00:00,  8.95s/batch, loss=0.0262]
# Epoch 7/25, Average Loss: 0.02616300629224719
# Epoch 8/25: 100%|██████████| 82/82 [12:18<00:00,  9.00s/batch, loss=0.0254]
# Epoch 8/25, Average Loss: 0.02543661682071482
# Epoch 9/25: 100%|██████████| 82/82 [12:20<00:00,  9.03s/batch, loss=0.0244]
# Epoch 9/25, Average Loss: 0.024361613388286858
# Epoch 10/25: 100%|██████████| 82/82 [12:40<00:00,  9.27s/batch, loss=0.024] 
# Epoch 10/25, Average Loss: 0.02402471621498102
# Epoch 11/25: 100%|██████████| 82/82 [12:37<00:00,  9.24s/batch, loss=0.0233]
# Epoch 11/25, Average Loss: 0.02328678470377515
# Epoch 12/25: 100%|██████████| 82/82 [12:25<00:00,  9.09s/batch, loss=0.0232]
# Epoch 12/25, Average Loss: 0.023177479234773937
# Epoch 13/25: 100%|██████████| 82/82 [12:16<00:00,  8.98s/batch, loss=0.0227]
# Epoch 13/25, Average Loss: 0.02268764790056682
# Epoch 14/25: 100%|██████████| 82/82 [12:09<00:00,  8.90s/batch, loss=0.0225]
# Epoch 14/25, Average Loss: 0.022537043000139843
# Epoch 15/25: 100%|██████████| 82/82 [12:14<00:00,  8.96s/batch, loss=0.022] 
# Epoch 15/25, Average Loss: 0.022021054630962815
# Epoch 16/25: 100%|██████████| 82/82 [1:01:07<00:00, 44.73s/batch, loss=0.0231] 
# Epoch 16/25, Average Loss: 0.023089414757744568
# Epoch 17/25: 100%|██████████| 82/82 [31:34<00:00, 23.11s/batch, loss=0.0212]   
# Epoch 17/25, Average Loss: 0.021172965922188466
# Epoch 18/25: 100%|██████████| 82/82 [46:11<00:00, 33.80s/batch, loss=0.0215]   
# Epoch 18/25, Average Loss: 0.0214947801901073
# Epoch 19/25: 100%|██████████| 82/82 [55:11<00:00, 40.38s/batch, loss=0.0212]   
# Epoch 19/25, Average Loss: 0.021193569526076317
# Epoch 20/25: 100%|██████████| 82/82 [53:20<00:00, 39.03s/batch, loss=0.0211]   
# Epoch 20/25, Average Loss: 0.02106804839085515
# Epoch 21/25: 100%|██████████| 82/82 [22:17<00:00, 16.31s/batch, loss=0.0207]   
# Epoch 21/25, Average Loss: 0.020741192396821047
# Epoch 22/25: 100%|██████████| 82/82 [46:52<00:00, 34.30s/batch, loss=0.0226]   
# Epoch 22/25, Average Loss: 0.022557636813783064
# Epoch 23/25: 100%|██████████| 82/82 [41:50<00:00, 30.61s/batch, loss=0.0201]   
# Epoch 23/25, Average Loss: 0.02006759480913965
# Epoch 24/25: 100%|██████████| 82/82 [1:15:16<00:00, 55.08s/batch, loss=0.0203]   
# Epoch 24/25, Average Loss: 0.02029608319536215
# Epoch 25/25: 100%|██████████| 82/82 [41:43<00:00, 30.53s/batch, loss=0.0203]   
# Epoch 25/25, Average Loss: 0.020283445988486453



In [10]:
# torch.save(nerf_model, "./nerf_model.pt")

In [11]:
nerf_model = torch.load("./nerf_model.pt")

In [19]:
reload(nerf)
reload(slam)
data = slam.inference_preprocessor(position=np.array([0,0,0]), direction=np.array([0,1,0]))
inference_dataloader = DataLoader(data, 2**14, shuffle=False)

Rotation: 
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]


In [20]:
img = nerf.infer(model=nerf_model, data_loader=inference_dataloader)
plt.imshow(img)

Inference Progress: 100%|██████████| 17/17 [00:38<00:00,  2.24s/batch]

torch.Size([268324, 64, 3])
torch.Size([268324, 64])
torch.Size([17172736])


RuntimeError: The size of tensor a (64) must match the size of tensor b (17172736) at non-singleton dimension 1